import React, { useEffect, useMemo, useState } from "react";
import "./App.css";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Bell, Check, CheckCircle2,
  ChevronRight, Clock3, Cpu, Download, FileText, Gauge, Info, LayoutDashboard,
  Menu, Pause, Play, Radio, Settings, ShieldCheck, Sparkles, Thermometer, Wrench, X
} from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Toaster, toast } from "sonner";

const healthTrend = [
  { time: "00", score: 92 }, { time: "04", score: 90 }, { time: "08", score: 91 },
  { time: "12", score: 88 }, { time: "16", score: 89 }, { time: "20", score: 86 }, { time: "Now", score: 87 }
];
const navItems = [
  ["overview", "Overview", LayoutDashboard], ["health", "Belt Health", ShieldCheck],
  ["inspection", "AI Inspection", Cpu], ["prediction", "Prediction", Clock3],
  ["reports", "Reports", FileText], ["settings", "Settings", Settings]
];
const sensors = [
  { label: "Vibration", value: "2.4", unit: "mm/s", trend: "Slight increase", icon: Activity, color: "cyan" },
  { label: "Temperature", value: "48.2", unit: "°C", trend: "Stable", icon: Thermometer, color: "amber" },
  { label: "Tension / Load", value: "71", unit: "%", trend: "Stable", icon: Gauge, color: "green" },
  { label: "Belt alignment", value: "4", unit: "mm offset", trend: "Within range", icon: Radio, color: "blue" }
];
const detections = [
  { type: "Splice tear", confidence: "92%", severity: "Moderate", time: "21:34", sector: "Joint #07", image: "https://images.unsplash.com/photo-1535923430552-0ce3cd477cc7?auto=format&fit=crop&w=1100&q=80" },
  { type: "Edge fraying", confidence: "88%", severity: "Low", time: "18:12", sector: "Return run", image: "https://images.unsplash.com/photo-1701328778019-e95dedbf5346?auto=format&fit=crop&w=1100&q=80" },
  { type: "Surface crack", confidence: "81%", severity: "Low", time: "14:48", sector: "Loading zone", image: "https://images.unsplash.com/photo-1535923430552-0ce3cd477cc7?auto=format&fit=crop&w=1100&q=80" }
];
const contributionData = [
  ["Vision damage", 82, "−5 points", "warning"], ["Vibration", 91, "−2 points", "good"],
  ["Acoustic", 94, "Normal", "good"], ["Temperature", 97, "Normal", "good"],
  ["Tension", 86, "−1 point", "good"], ["Alignment", 92, "Normal", "good"]
];
const reports = [
  ["29 Aug 2026", "87", "3", "147 h", "Daily health report"], ["28 Aug 2026", "91", "1", "163 h", "Daily health report"],
  ["27 Aug 2026", "92", "0", "171 h", "Daily health report"], ["26 Aug 2026", "94", "0", "179 h", "Daily health report"]
];

function StatusPill({ children, tone = "green" }) { return <span className={`status-pill ${tone}`} data-testid="status-pill">● {children}</span>; }
function Panel({ children, className = "" }) { return <section className={`panel ${className}`}>{children}</section>; }
function SectionHeading({ eyebrow, title, action }) { return <div className="section-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{action}</div>; }
function Sparkline({ tone = "cyan" }) { return <div className={`sparkline ${tone}`} aria-hidden="true"><span /><span /><span /><span /><span /><span /><span /></div>; }
function SensorCard({ sensor }) {
  const Icon = sensor.icon;
  return <div className="sensor-card" data-testid={`sensor-card-${sensor.label.toLowerCase().replaceAll(" ", "-")}`}>
    <div className="sensor-top"><div className={`icon-box ${sensor.color}`}><Icon size={17} /></div><span className="sensor-name">{sensor.label}</span><StatusPill>Normal</StatusPill></div>
    <div className="sensor-reading"><strong>{sensor.value}</strong><span>{sensor.unit}</span></div>
    <div className="sensor-bottom"><span>{sensor.trend}</span><Sparkline tone={sensor.color} /></div>
  </div>;
}
function HealthRing({ score = 87 }) { return <div className="health-ring" style={{ "--score": `${score * 3.6}deg` }}><div><strong data-testid="health-score">{score}</strong><span>/100</span><small>HEALTHY</small></div></div>; }

function Overview({ setTab, live, setLive, runScan }) {
  return <div className="page-stack" data-testid="overview-page">
    <div className="hero-card"><div className="hero-copy"><div className="eyebrow cyan-text"><span className="live-dot" /> LIVE OPERATIONS / PLANT 02</div><h1>Know your belt.<br /><em>Before it stops.</em></h1><p>Real-time health intelligence for Conveyor C-07. The operator view translates complex signals into one clear next action.</p><div className="hero-actions"><button className="button primary" onClick={() => setTab("inspection")} data-testid="hero-inspection-button">Open AI inspection <ChevronRight size={16} /></button><button className="button ghost" onClick={() => setLive(!live)} data-testid="hero-live-toggle">{live ? <Pause size={15} /> : <Play size={15} />} {live ? "Pause live feed" : "Resume live feed"}</button></div></div><div className="hero-visual"><div className="hero-grid" /><div className="conveyor-line"><span className="belt-node ok">01</span><span className="belt-node ok">02</span><span className="belt-node warn">!</span><span className="belt-node ok">04</span></div><div className="hero-visual-label"><span>CONVEYOR C-07</span><b>1,420 m span</b></div></div></div>
    <div className="stat-grid">
      <Panel className="health-feature"><div className="card-kicker">01 / BELT HEALTH <Info size={14} /></div><div className="health-layout"><HealthRing /><div><h3>Healthy & operating</h3><p>Strong overall condition with one moderate splice issue.</p><button className="text-button" onClick={() => setTab("health")} data-testid="health-details-button">Why is it 87? <ArrowUpRight size={15} /></button></div></div><div className="progress-line"><span style={{ width: "87%" }} /></div><div className="trend-note"><ArrowDownRight size={14} /> 3 points in the last 24 hours</div></Panel>
      <Panel className="rul-feature"><div className="card-kicker">02 / PREDICTED LIFE <Clock3 size={14} /></div><div className="big-number">147 <small>HRS</small></div><h3>About 6 days remaining</h3><p>Low risk for the next 48 hours.</p><button className="text-button" onClick={() => setTab("prediction")} data-testid="rul-details-button">View prediction <ArrowUpRight size={15} /></button></Panel>
      <Panel className="alert-feature"><div className="card-kicker">03 / ACTIVE ALERTS <Bell size={14} /></div><div className="alert-count"><strong>1</strong><div><h3>Attention needed</h3><p>Moderate splice tear detected at Joint #07.</p></div></div><button className="button small warning" onClick={() => setTab("inspection")} data-testid="alert-review-button">Review detection</button></Panel>
    </div>
    <div className="two-col"><Panel><SectionHeading eyebrow="04 / TELEMETRY" title="Live sensor signals" action={<StatusPill>System online</StatusPill>} /><div className="sensor-grid">{sensors.map(sensor => <SensorCard key={sensor.label} sensor={sensor} />)}</div><div className="panel-footer"><span><span className="live-dot" /> Updating every 3 seconds</span><button className="text-button" onClick={() => toast.info("Detailed sensor monitoring is ready in the Live Monitor view.")} data-testid="sensor-detail-button">Open detailed monitor <ChevronRight size={15} /></button></div></Panel><Panel className="timeline-panel"><SectionHeading eyebrow="05 / EVENT TIMELINE" title="What happened today" /><div className="timeline">{[["21:34", "Splice tear detected", "Moderate · 92% confidence", "warn"], ["18:40", "System returned to normal", "All operating signals stable", "good"], ["13:18", "Vibration anomaly", "Small increase on drive pulley", "cyan"], ["08:14", "System started", "Shift B · Operator Admin", "good"]].map((e, i) => <div className="timeline-item" key={e[0]}><span className={`timeline-dot ${e[3]}`} /><time>{e[0]}</time><div><strong>{e[1]}</strong><p>{e[2]}</p></div></div>)}</div><button className="text-button" onClick={() => setTab("reports")} data-testid="timeline-reports-button">View all activity <ChevronRight size={15} /></button></Panel></div>
    <Panel className="recommendation"><div className="recommendation-icon"><Sparkles size={20} /></div><div><div className="eyebrow">AI RECOMMENDATION</div><h3>Continue operation — schedule inspection within 48 hours.</h3><p>Based on the moderate splice tear, rising vibration, and 147-hour remaining useful life estimate.</p></div><button className="button primary" onClick={() => toast.success("Inspection task added to the maintenance queue.")} data-testid="schedule-inspection-button"><Wrench size={15} /> Schedule inspection</button></Panel>
  </div>;
}

function HealthPage({ setTab }) { return <div className="page-stack" data-testid="health-page"><SectionHeading eyebrow="BELT HEALTH / EXPLAINABILITY" title="Why is the belt health 87?" action={<button className="button ghost" onClick={() => toast.success("Health profile exported.")} data-testid="health-export-button"><Download size={15} /> Export profile</button>} /><div className="health-detail-grid"><Panel className="contribution-panel"><div className="detail-score"><HealthRing /><div><div className="eyebrow">CURRENT INDEX</div><h3>Healthy with one watch item</h3><p>Lower scores mean the signal is moving further from learned normal operation.</p></div></div><div className="contributions">{contributionData.map(([name, score, impact, tone]) => <div className="contribution" key={name} data-testid={`contribution-${name.toLowerCase().replaceAll(" ", "-")}`}><div><span>{name}</span><b>{score}</b></div><div className="bar"><i className={tone} style={{ width: `${score}%` }} /></div><small>{impact}</small></div>)}</div></Panel><Panel><SectionHeading eyebrow="PRIMARY REASONS" title="What changed" /><div className="why-list"><div><span className="number">01</span><div><strong>Moderate splice tear</strong><p>Vision model lowered health by 5 points</p></div><b className="warning-text">−5</b></div><div><span className="number">02</span><div><strong>Rising vibration</strong><p>Drive pulley signal slightly above baseline</p></div><b className="warning-text">−2</b></div><div><span className="number">03</span><div><strong>All other systems normal</strong><p>Temperature, tension and alignment stable</p></div><b className="good-text">+0</b></div></div><div className="insight"><Info size={17} /><p>The main contributor to today’s health reduction is the detected splice tear.</p></div></Panel></div><Panel><SectionHeading eyebrow="24-HOUR HISTORY" title="Health score trend" action={<span className="muted-label">Current <b className="cyan-text">87</b></span>} /><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={healthTrend}><defs><linearGradient id="healthFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#56e0dc" stopOpacity={.28} /><stop offset="100%" stopColor="#56e0dc" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#263443" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="time" stroke="#657586" tickLine={false} axisLine={false} /><YAxis domain={[70, 100]} stroke="#657586" tickLine={false} axisLine={false} /><Tooltip contentStyle={{ background: "#17212a", border: "1px solid #304354", borderRadius: 8, color: "#f2f7f7" }} /><Area type="monotone" dataKey="score" stroke="#56e0dc" strokeWidth={3} fill="url(#healthFill)" /></AreaChart></ResponsiveContainer></div></Panel><button className="back-link" onClick={() => setTab("overview")} data-testid="health-back-button">← Back to overview</button></div>; }

function InspectionPage() { const [selected, setSelected] = useState(detections[0]); return <div className="page-stack" data-testid="inspection-page"><SectionHeading eyebrow="COMPUTER VISION / LIVE CAMERA" title="AI inspection" action={<button className="button primary" onClick={() => toast.success("Scan complete — 3 belt events reviewed.")} data-testid="run-scan-button"><Sparkles size={15} /> Run new scan</button>} /><div className="inspection-grid"><Panel className="detection-list"><div className="card-kicker">RECENT DETECTIONS <span>{detections.length}</span></div>{detections.map(item => <button className={`detection-row ${selected.type === item.type ? "selected" : ""}`} key={item.type} onClick={() => setSelected(item)} data-testid={`detection-${item.type.toLowerCase().replaceAll(" ", "-")}`}><div className="detection-thumb" style={{ backgroundImage: `url(${item.image})` }}><span>AI</span></div><div><strong>{item.type}</strong><p>{item.sector} · {item.time}</p></div><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span></button>)}</Panel><Panel className="inspection-detail"><div className="inspection-image" style={{ backgroundImage: `url(${selected.image})` }}><div className="scan-lines" /><div className="bounding-box"><span>TEAR · {selected.confidence}</span></div><div className="image-caption"><span>CAM-07 / LIVE</span><span>21:34:08 UTC</span></div></div><div className="detail-meta"><div><div className="eyebrow">DETECTION / {selected.time}</div><h3>{selected.type} detected</h3><p>AI confidence <b className="cyan-text">{selected.confidence}</b> · Location <b>{selected.sector}</b></p></div><StatusPill tone="amber">{selected.severity} severity</StatusPill></div><div className="action-box"><Wrench size={18} /><div><strong>Recommended action</strong><p>Schedule a splice inspection during the next planned maintenance window.</p></div><button className="button small primary" onClick={() => toast.success("Work order created for Joint #07.")} data-testid="inspection-work-order-button">Create work order</button></div></Panel></div></div>; }

function PredictionPage() { return <div className="page-stack" data-testid="prediction-page"><SectionHeading eyebrow="PREDICTIVE HEALTH / RUL" title="What happens next?" action={<StatusPill>Model confidence 91%</StatusPill>} /><div className="prediction-stats"><Panel><div className="eyebrow">CURRENT HEALTH</div><div className="big-number cyan-text">87 <small>/ 100</small></div><StatusPill>Healthy</StatusPill></Panel><Panel><div className="eyebrow">PREDICTED LIFE</div><div className="big-number">147 <small>HRS</small></div><p>~6 days until critical threshold</p></Panel><Panel><div className="eyebrow">FAILURE RISK / 72 HRS</div><div className="big-number amber-text">18<small>%</small></div><StatusPill tone="amber">Low — moderate</StatusPill></Panel></div><Panel><SectionHeading eyebrow="MODEL PROJECTION" title="Predicted health trend" /><div className="prediction-chart"><div className="threshold-line">CRITICAL THRESHOLD · 60</div><div className="projection-path"><span className="path-point p1" /><span className="path-point p2" /><span className="path-point p3" /><span className="path-point p4" /></div><div className="axis-labels"><span>NOW</span><span>48 HOURS</span><span>4 DAYS</span><span>6 DAYS</span></div></div></Panel><div className="two-col"><Panel><SectionHeading eyebrow="RISK WINDOW" title="Failure probability" />{[["24 hours", "Low", "8%", "good"], ["48 hours", "Low", "12%", "good"], ["72 hours", "Moderate", "18%", "amber"], ["7 days", "High", "41%", "danger"]].map(item => <div className="risk-row" key={item[0]}><span>{item[0]}</span><b className={`${item[3]}-text`}>{item[1]}</b><strong>{item[2]}</strong></div>)}</Panel><Panel className="maintenance-card"><div className="card-kicker">MAINTENANCE WINDOW</div><h3>Best time to intervene</h3><p>Reserve a planned 18-hour window between <b>02–04 Sep 2026</b>, before risk accelerates.</p><button className="button primary" onClick={() => toast.success("Maintenance window reserved.")} data-testid="reserve-window-button"><Wrench size={15} /> Reserve window</button></Panel></div></div>; }

function ReportsPage() { return <div className="page-stack" data-testid="reports-page"><SectionHeading eyebrow="REPORT CENTER / AUDIT TRAIL" title="Daily health reports" action={<button className="button primary" onClick={() => toast.success("Report bundle prepared for download.")} data-testid="export-reports-button"><Download size={15} /> Export bundle</button>} /><Panel className="reports-panel"><div className="table-intro"><div><h3>Conveyor C-07 report archive</h3><p>Every day, one clear record of health, alerts, and recommended action.</p></div><span className="muted-label">4 reports</span></div><div className="report-table"><div className="report-head"><span>DATE</span><span>HEALTH</span><span>ALERTS</span><span>RUL</span><span>REPORT</span><span /></div>{reports.map((row, i) => <div className="report-row" key={row[0]} data-testid={`report-row-${i}`}><span><b>{row[0]}</b><small>Conveyor C-07</small></span><strong className="cyan-text">{row[1]}</strong><span>{row[2]}</span><span>{row[3]}</span><span>{row[4]}</span><button className="icon-button" onClick={() => toast.success(`${row[0]} report downloaded.`)} data-testid={`download-report-${i}`}><Download size={15} /></button></div>)}</div></Panel><div className="report-highlights"><Panel><div className="eyebrow">THIS MONTH</div><div className="big-number">92<small> avg health</small></div><p>Health remains above the safe operating threshold.</p></Panel><Panel><div className="eyebrow">MAINTENANCE AVOIDED</div><div className="big-number cyan-text">18<small> hrs</small></div><p>Estimated downtime avoided through early detection.</p></Panel></div></div>; }

function SettingsPage() { const [saved, setSaved] = useState(false); return <div className="page-stack" data-testid="settings-page"><SectionHeading eyebrow="SYSTEM / CONFIGURATION" title="Settings" action={<button className="button primary" onClick={() => { setSaved(true); toast.success("Configuration saved."); }} data-testid="save-settings-button"><Check size={15} /> Save changes</button>} /><div className="settings-grid"><Panel><div className="card-kicker">CONVEYOR PROFILE</div><label>Conveyor name<input defaultValue="Conveyor C-07" data-testid="conveyor-name-input" /></label><label>Plant location<input defaultValue="Plant 02 · North transfer station" data-testid="plant-location-input" /></label><label>Health refresh interval<select defaultValue="3 seconds" data-testid="refresh-interval-select"><option>3 seconds</option><option>10 seconds</option><option>30 seconds</option></select></label></Panel><Panel><div className="card-kicker">ALERT THRESHOLDS</div><label>Critical health score<input type="number" defaultValue="60" data-testid="critical-score-input" /></label><label>RUL maintenance trigger<input defaultValue="48 hours" data-testid="rul-trigger-input" /></label><div className="toggle-row"><span><b>Sound alerts</b><small>Play a sound for new critical events</small></span><button className="toggle on" data-testid="sound-alert-toggle" onClick={e => e.currentTarget.classList.toggle("on")}><i /></button></div></Panel></div>{saved && <div className="saved-banner" data-testid="settings-saved-message"><CheckCircle2 size={16} /> Configuration saved for this browser session.</div>}</div>; }

export default function App() {
  const [tab, setTab] = useState("overview"); const [live, setLive] = useState(true); const [mobileMenu, setMobileMenu] = useState(false); const [clock, setClock] = useState(new Date());
  useEffect(() => { const timer = setInterval(() => setClock(new Date()), 1000); return () => clearInterval(timer); }, []);
  const page = useMemo(() => ({ overview: ["Overview", "Operator cockpit"], health: ["Belt Health", "Health explained"], inspection: ["AI Inspection", "Visual detections"], prediction: ["Prediction", "Remaining useful life"], reports: ["Reports", "Daily records"], settings: ["Settings", "System configuration"] }[tab]), [tab]);
  const runScan = () => toast.success("AI scan complete — all 142 belt segments checked.");
  return <div className="app-shell"><Toaster position="top-right" theme="dark" /><aside className={`sidebar ${mobileMenu ? "open" : ""}`}><div className="brand"><div className="brand-mark"><Activity size={21} /></div><div><strong>NMDC</strong><span>SMART CONVEYOR</span></div><button className="close-menu" onClick={() => setMobileMenu(false)} data-testid="close-menu-button"><X size={18} /></button></div><div className="conveyor-selector"><span>MONITORING</span><button onClick={() => toast.info("Conveyor selector is ready for multi-conveyor data.")} data-testid="conveyor-selector"><b>C-07</b><span>North transfer station</span><ChevronRight size={15} /></button></div><nav>{navItems.map(([id, label, Icon]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => { setTab(id); setMobileMenu(false); }} data-testid={`nav-${id}`}><Icon size={17} /><span>{label}</span>{id === "inspection" && <i className="nav-badge">3</i>}</button>)}</nav><div className="sidebar-footer"><StatusPill>System online</StatusPill><p>Last sync <b>21:58:32</b></p><small>PS26008 · v1.4.2</small></div></aside><main className="main-area"><header className="topbar"><button className="menu-button" onClick={() => setMobileMenu(true)} data-testid="open-menu-button"><Menu size={20} /></button><div><div className="breadcrumb">{page[0]} <ChevronRight size={13} /> <span>{page[1]}</span></div><div className="topbar-title">Conveyor C-07 <StatusPill>Running safely</StatusPill></div></div><div className="topbar-actions"><div className="clock"><span>29 AUG 2026</span><b>{clock.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false })}</b></div><button className="icon-button" onClick={() => toast.info("No critical alerts. One item needs attention.")} data-testid="notifications-button"><Bell size={17} /><i /></button><div className="operator"><span>AD</span><div><b>Admin</b><small>Shift B · Plant 02</small></div></div></div></header><div className="content">{tab === "overview" && <Overview setTab={setTab} live={live} setLive={setLive} runScan={runScan} />}{tab === "health" && <HealthPage setTab={setTab} />}{tab === "inspection" && <InspectionPage />}{tab === "prediction" && <PredictionPage />}{tab === "reports" && <ReportsPage />}{tab === "settings" && <SettingsPage />}</div></main></div>;
}